_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.9.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.7
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
batch_size:
    value: 128
epochs:
    value: 1
hidden_dim:
    value: 512
input_dim:
    value: 512
lr:
    value: 0.001
sparsity_lambda:
    value: 0.0001
